<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssignedTasksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('assigned_tasks')->truncate();

        DB::unprepared(<<<'SQL'
INSERT INTO `assigned_tasks` (`id`, `assignor_id`, `assignee_id`, `house_id`, `mls_id`, `category`, `subcategory`, `is_qa_task`, `is_draft`, `title`, `description`, `task_description`, `description_document_cta_button_label`, `remember_instructions`, `primary_cta_label`, `secondary_cta_label`, `image_link`, `image_caption`, `video_link`, `video_caption`, `sale_price`, `task_explain_doc`, `status`, `cancelled_flag`, `is_task_mandatory`, `is_acknowledged_mandatory`, `acknowledgement_statement`, `acknowledgement_timestamp`, `is_comment_mandatory`, `question_to_seller`, `comment`, `rejection_reason`, `is_doc_mandatory`, `reminder_id`, `doc_path`, `master_doc_type`, `master_id`, `custom_task_flag`, `accept_comment`, `created_at`, `updated_at`, `comment_timestamp`, `accept_comment_timestamp`, `reject_comment_timestamp`, `virtual_tour`) VALUES
(1, 30, 1, 1, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:37:40', '2018-11-07 03:44:57', NULL, NULL, NULL, NULL),
(2, 31, 2, 2, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:37:40', '2018-11-07 03:45:44', NULL, NULL, NULL, NULL),
(3, 31, 2, 2, NULL, 3, NULL, 0, 0, 'NC - Residential Property and Owners Association Disclosure', 'Takes approximately 30 minutes to complete. Let\'s Start', 'Your Listing Agent requires certain docs like the Listing Agreement, Agency Disclosure, and Property Details Input Forms. The sooner you complete these, the quicker your listing will be online.', 'Launch Now', 'Use your Houzeo listing and data from Zillow, Redfin, and your tax records to fill this form quicker*Leave the fields you don\'t know the answer to blank. The agent will follow-up if they need additional info from you*The more you can fill, the better. It\'ll reduce back and forth and get your listing live faster*If there are multiple parties listed on the title, each one needs to sign these documents.', 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:37:40', '2018-11-07 03:48:56', NULL, NULL, NULL, NULL),
(4, 31, 2, 3, NULL, 3, NULL, 0, 0, 'NC - Mineral and Oil & Gas Rights Mandatory Disclosure', 'Takes approximately 10 minutes to complete. Let\'s Start', 'Your Listing Agent requires certain docs like the Listing Agreement, Agency Disclosure, and Property Details Input Forms. The sooner you complete these, the quicker your listing will be online.', 'Launch Now', 'Use your Houzeo listing and data from Zillow, Redfin, and your tax records to fill this form quicker*Leave the fields you don\'t know the answer to blank. The agent will follow-up if they need additional info from you*The more you can fill, the better. It\'ll reduce back and forth and get your listing live faster*If there are multiple parties listed on the title, each one needs to sign these documents.', 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:37:40', '2018-11-07 03:49:25', NULL, NULL, NULL, NULL),
(5, 32, 3, 4, NULL, 2, NULL, 0, 0, 'Share via Facebook', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Facebook', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:49:25', '2018-11-07 12:51:02', NULL, NULL, NULL, NULL),
(6, 32, 3, 4, NULL, 2, NULL, 0, 0, 'Share via Twitter', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Twitter', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 03:49:25', '2018-11-07 13:18:06', NULL, NULL, NULL, NULL),
(7, 33, 3, 4, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:44:23', NULL, NULL, NULL, NULL),
(8, 33, 3, 4, NULL, 1, NULL, 0, 0, 'Listing Agreement', 'Takes 3 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:44:33', NULL, NULL, NULL, NULL),
(9, 33, 3, 4, NULL, 1, NULL, 0, 0, 'Agency Disclosure', 'Takes 3 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:44:42', NULL, NULL, NULL, NULL),
(10, 33, 3, 5, NULL, 1, NULL, 0, 0, 'MLS Data Input Single Family Home', 'Takes 30 minutes to complete. Let\u2019s start', NULL, 'Launch Now', 'Use your Houzeo listing and data from Zillow, Redfin, and your tax records to fill this form quicker*Leave the fields you don\'t know the answer to blank. The agent will follow-up if they need additional info from you*The more you can fill, the better. It\'ll reduce back and forth and get your listing live faster*If there are multiple parties listed on the title, each one needs to sign these documents.', 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:44:53', NULL, NULL, NULL, NULL),
(11, 33, 3, 5, NULL, 1, NULL, 0, 0, 'North Carolina Required Property Sketch', 'Takes between 5 mins to 1 hour to complete.', 'Please measure your home and draft it on a sheet of paper or if you have a copy of your appraisal, attach the measurement page. Here\'s a link to show you how to measure, calculate and sketch your square footage', 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:45:02', NULL, NULL, NULL, NULL),
(12, 31, 3, 5, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:45:12', NULL, NULL, NULL, NULL),
(13, 31, 1, 1, NULL, 3, NULL, 0, 0, 'NC - Residential Property and Owners Association Disclosure', 'Takes approximately 30 minutes to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:45:21', NULL, NULL, NULL, NULL),
(14, 31, 7, 10, NULL, 3, NULL, 0, 0, 'NC - Mineral and Oil & Gas Rights Mandatory Disclosure', 'Takes approximately 10 minutes to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:45:30', NULL, NULL, NULL, NULL),
(15, 34, 8, 12, NULL, 2, NULL, 0, 0, 'Share via Facebook', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Facebook', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '0', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:45:30', '2018-11-07 10:45:30', NULL, NULL, NULL, NULL),
(16, 34, 9, 13, NULL, 2, NULL, 0, 0, 'Share via Twitter', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Twitter', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '0', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:45:30', '2018-11-07 10:45:30', NULL, NULL, NULL, NULL),
(17, 35, 8, 12, 0, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-09 05:06:52', '2021-03-12 06:57:43', NULL, NULL, NULL, NULL),
(18, 35, 10, 15, 0, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-09 05:06:52', '2021-03-12 06:57:43', NULL, NULL, NULL, NULL),
(19, 34, 8, 12, 0, 2, NULL, 0, 0, 'Share via Facebook', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Facebook', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '2', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-12 22:53:39', '2021-03-12 06:57:43', NULL, NULL, NULL, NULL),
(20, 34, 8, 12, 0, 2, NULL, 0, 0, 'Share via Twitter', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Twitter', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '2', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-12 22:53:39', '2021-03-12 06:57:43', NULL, NULL, NULL, NULL),
(21, 33, 11, 16, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-14 22:21:09', '2018-11-14 22:28:43', NULL, NULL, NULL, NULL),
(22, 31, 11, 16, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-14 22:21:09', '2018-11-14 22:33:26', NULL, NULL, NULL, NULL),
(23, 34, 11, 16, NULL, 2, NULL, 0, 0, 'Share via Facebook', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Facebook', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-14 22:33:26', '2018-11-14 22:39:47', NULL, NULL, NULL, NULL),
(24, 34, 11, 16, NULL, 2, NULL, 0, 0, 'Share via Twitter', 'Takes 1 min to complete. Let\'s start', NULL, 'Share on Twitter', NULL, 'Mark as Complete', 'Save for Later', NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, 0, NULL, '2018-11-14 22:33:26', '2018-11-14 22:38:58', NULL, NULL, NULL, NULL),
(25, 33, 11, 16, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-16 09:29:03', '2018-12-31 13:09:02', NULL, NULL, NULL, NULL),
(26, 846, 568, 40, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-16 09:29:03', '2018-12-31 13:09:11', NULL, NULL, NULL, NULL),
(27, 295, 847, 41, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-21 06:13:56', '2018-11-21 07:26:39', NULL, NULL, NULL, NULL),
(28, 295, 847, 31, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-21 06:13:56', '2018-11-21 06:13:56', NULL, NULL, NULL, NULL),
(29, 296, 568, 55, NULL, 1, NULL, 0, 0, 'Houzeo Relationship Agreement & Disclosures', 'Takes 3 mins to complete. Let\'s start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:47:23', NULL, NULL, NULL, NULL),
(30, 296, 568, 44, NULL, 1, NULL, 0, 0, 'Listing Agreement', 'Takes 3 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:47:42', NULL, NULL, NULL, NULL),
(31, 296, 568, 54, NULL, 1, NULL, 0, 0, 'Agency Disclosure', 'Takes 3 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:47:53', NULL, NULL, NULL, NULL),
(32, 296, 568, 53, NULL, 1, NULL, 0, 0, 'MLS Data Input Single Family Home', 'Takes 30 minutes to complete. Let\u2019s start', NULL, 'Launch Now', 'Use your Houzeo listing and data from Zillow, Redfin, and your tax records to fill this form quicker*Leave the fields you don\'t know the answer to blank. The agent will follow-up if they need additional info from you*The more you can fill, the better. It\'ll reduce back and forth and get your listing live faster*If there are multiple parties listed on the title, each one needs to sign these documents.', 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-07 10:43:24', '2018-11-07 10:44:53', NULL, NULL, NULL, NULL),
(33, 296, 568, 52, NULL, 1, NULL, 0, 0, 'North Carolina Required Property Sketch', 'Takes between 5 mins to 1 hour to complete.', 'Please measure your home and draft it on a sheet of paper or if you have a copy of your appraisal, attach the measurement page. Here\'s a link to show you how to measure, calculate and sketch your square footage', 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:48:17', NULL, NULL, NULL, NULL),
(34, 296, 568, 52, NULL, 3, NULL, 0, 0, 'Federal Lead Paint Disclosure', 'Takes 5 mins to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:50:12', NULL, NULL, NULL, NULL),
(35, 296, 568, 51, NULL, 3, NULL, 0, 0, 'NC - Residential Property and Owners Association Disclosure', 'Takes approximately 30 minutes to complete. Let\'s Start', NULL, 'Launch Now', NULL, 'Mark as Complete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, '2018-11-26 14:03:25', '2018-12-14 15:50:56', NULL, NULL, NULL, NULL);
SQL
        );
    }
}
